python3 train_datagen.py --path results/hidden --network iresnet --cudnn_deterministic --min_sample 0 --hidden 16 --L 200 --kernel 7 --depth 5 --max_hidden 32 --filename ogle_data_15.pkl --ngpu 1 --K 5 --embedding ../data/ogle_15.unitsphere.pickle --classnames ../data/ogle_class_names_15.txt --hierarchy ../data/ogle.parent-child_15.txt --classification 'hidden' --maxsize 200 --max_epoch 40 --no-log

python3 train_datagen.py --path results/hidden --network iresnet --cudnn_deterministic --min_sample 0 --hidden 16 --L 200 --kernel 7 --depth 5 --max_hidden 32 --filename ogle_data_15.pkl --ngpu 1 --K 5 --embedding ../data/ogle_15.unitsphere.pickle --classnames ../data/ogle_class_names_15.txt --hierarchy ../data/ogle.parent-child_15.txt --classification 'hidden' --maxsize 150 --max_epoch 40 --no-log

python3 train_datagen.py --path results/hidden --network iresnet --cudnn_deterministic --min_sample 0 --hidden 16 --L 200 --kernel 7 --depth 5 --max_hidden 32 --filename ogle_data_15.pkl --ngpu 1 --K 5 --embedding ../data/ogle_15.unitsphere.pickle --classnames ../data/ogle_class_names_15.txt --hierarchy ../data/ogle.parent-child_15.txt --classification 'hidden' --maxsize 100 --max_epoch 40 --no-log

python3 train_datagen.py --path results/hidden --network iresnet --cudnn_deterministic --min_sample 0 --hidden 16 --L 200 --kernel 7 --depth 5 --max_hidden 32 --filename ogle_data_15.pkl --ngpu 1 --K 5 --embedding ../data/ogle_15.unitsphere.pickle --classnames ../data/ogle_class_names_15.txt --hierarchy ../data/ogle.parent-child_15.txt --classification 'hidden' --maxsize 75 --max_epoch 40 --no-log

python3 train_datagen.py --path results/hidden --network iresnet --cudnn_deterministic --min_sample 0 --hidden 16 --L 200 --kernel 7 --depth 5 --max_hidden 32 --filename ogle_data_15.pkl --ngpu 1 --K 5 --embedding ../data/ogle_15.unitsphere.pickle --classnames ../data/ogle_class_names_15.txt --hierarchy ../data/ogle.parent-child_15.txt --classification 'hidden' --maxsize 50 --max_epoch 40 --no-log

python3 train_datagen.py --path results/hidden --network iresnet --cudnn_deterministic --min_sample 0 --hidden 16 --L 200 --kernel 7 --depth 5 --max_hidden 32  --filename ogle_data_15.pkl --ngpu 1 --K 5 --embedding ../data/ogle_15.unitsphere.pickle --classnames ../data/ogle_class_names_15.txt --hierarchy ../data/ogle.parent-child_15.txt --classification 'hidden' --maxsize 25 --max_epoch 40 --no-log

python3 train_datagen.py --path results/hidden --network iresnet --cudnn_deterministic --min_sample 0 --hidden 16 --L 200 --kernel 7 --depth 5 --max_hidden 32 --filename ogle_data_15.pkl --ngpu 1 --K 5 --embedding ../data/ogle_15.unitsphere.pickle --classnames ../data/ogle_class_names_15.txt --hierarchy ../data/ogle.parent-child_15.txt --classification 'hidden' --maxsize 10 --max_epoch 40 --no-log

python3 train_datagen.py --path results/hidden --network iresnet --cudnn_deterministic --min_sample 0 --hidden 16 --L 200 --kernel 7 --depth 5 --max_hidden 32 --filename ogle_data_15.pkl --ngpu 1 --K 5 --embedding ../data/ogle_15.unitsphere.pickle --classnames ../data/ogle_class_names_15.txt --hierarchy ../data/ogle.parent-child_15.txt --classification 'hidden' --maxsize 5 --max_epoch 40 --no-log

python3 train_datagen.py --path results/hidden --network iresnet --cudnn_deterministic --min_sample 0 --hidden 16 --L 200 --kernel 7 --depth 5 --max_hidden 32  --filename ogle_data_15.pkl --ngpu 1 --K 5 --embedding ../data/ogle_15.unitsphere.pickle --classnames ../data/ogle_class_names_15.txt --hierarchy ../data/ogle.parent-child_15.txt --classification 'hidden' --maxsize 1 --max_epoch 40 --no-log